Flask flaskr tutorial :
https://flask.palletsprojects.com/en/3.0.x/tutorial/blog/

Added blog functionality.

  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\flaskr\__init__.py", line 16, in create_app
    from . import blog
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\flaskr\blog.py", line 23, in <module>
    def create():
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\flaskr\auth.py", line 97, in login_required
    return wrapped_view()
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\flaskr\auth.py", line 93, in wrapped_view
    if g.user is None:
  File "C:\Users\Alain\PycharmProjects\flask\venv\lib\site-packages\werkzeug\local.py", line 311, in __get__
    obj = instance._get_current_object()
  File "C:\Users\Alain\PycharmProjects\flask\venv\lib\site-packages\werkzeug\local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.