Flask flaskr tutorial :
https://flask.palletsprojects.com/en/3.0.x/tutorial/blog/

Project isn't working.

Flasks automatically detects the factory function "create_app" in a correct setting. As is however, flask instead calls random functions from blog.py which then throw errors because the app context is not defined. The context is of course not defined as the framework didn't start the app yet...

C:\Users\Alain\PycharmProjects\flask\flask-tutorial>flask --app flaskr run --debug
Traceback (most recent call last):
  File "C:\Users\Alain\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Alain\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\flask\cli.py", line 1050, in main
    cli.main()
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\flask\cli.py", line 911, in run_command
    raise e from None
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\flask\cli.py", line 897, in run_command
    app = info.load_app()
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\flask\cli.py", line 308, in load_app
    app = locate_app(import_name, name)
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\flask\cli.py", line 235, in locate_app
    return find_best_app(module)
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\flask\cli.py", line 63, in find_best_app
    app = app_factory()
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\flaskr\__init__.py", line 36, in create_app
    from . import blog
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\flaskr\blog.py", line 41, in <module>
    @login_required
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\flaskr\auth.py", line 21, in login_required
    return wrapped_view()
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\flaskr\auth.py", line 17, in wrapped_view
    if g.user is None:
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\werkzeug\local.py", line 316, in __get__
    obj = instance._get_current_object()
  File "C:\Users\Alain\PycharmProjects\flask\flask-tutorial\venv\lib\site-packages\werkzeug\local.py", line 513, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.